### ISSUE TITLE
Resizable window/panel 

### ISSUE THREAD

**Issue by dgmaia** [sonburn/symbol-swapper#41]
Would be possible to make the main window/panel resizable?

The symbols I have been working on all have really long names, its been a bit difficult to work without be able to read its full name. 

![Screen Shot 2020-01-27 at 9 58 29 AM](https://user-images.githubusercontent.com/3528298/73141710-f0d1e080-40eb-11ea-8cb4-334a2c00b9c7.png)

**Comment by sonburn** [comment]
@dgmaia I finally found some time to make some long overdue plugin updates, and I think I fixed this issue. Can you download version 0.20 and let me know if your experience is improved?

**Comment by dgmaia** [comment]
Thanks man, definitely better now.
Can't resize the panel but the dropdown list expands to show all items names.
Cheers, really appreciate.

**Comment by sonburn** [comment]
Glad to hear it, and thanks for using my plugin!

**Comment by sonburn** [comment]
@dgmaia I had to revert the plugin to the previous select box implementation (which cut off long names) because we lost the ability to search by typing with the newer select box I implemented.

So as a compromise, I am now setting a tooltip on the select box, which shows the full name of the currently selected item. It's not ideal, but I don't have a lot of options (without expanding the window, which is a last resort). Please let me know how it works for you.

**Comment by dgmaia** [comment]
Thanks for the heads up
I'm testing right now.

**Comment by dgmaia** [comment]
Yeah =/
It's not ideal for my use case... tooltip takes a while to popup.
But if you really need to revert to the old way, **it does help**.

I didn't know was possible to type on the field.
When I see a select box, I think that I have to pick an option from a list.
But I couldn't make it work.
Typing something didn't filter the options and hitting 'return/enter' or tab, didn't change it either.
